export const menuOptions = [
  {
    id: 1,
    name: 'Dashboard',
    icon: 'fa fa-dashboard fa-fw',
    route: 'dashboard',
    isSelected: false,
  },
  {
    id: 2,
    name: 'Riders',
    route: 'riders',
    icon: 'fa-solid fa-user',
    isSelected: false,
  },
  {
    id: 3,
    name: 'Drivers',
    route: 'drivers',
    icon: 'icon-steering-wheel',
    isSelected: false,
  },
  {
    id: 4,
    name: 'Rides',
    route: 'rides',
    icon: 'fa-solid fa-car',
    isSelected: false,
  },
  // {
  //   id: 5,
  //   name: 'Manual Ride Booking',
  //   route: 'manual-ride-booking',
  //   icon: '',
  //   isSelected: false,
  // },
  {
    id: 6,
    name: 'Vehicle',
    icon: 'icon-cab',
    route: 'vehicle',
    isSelected: false,
  },
  // {
  //   id: 7,
  //   name: 'Localization',
  //   route: 'localization',
  //   icon: '',
  //   isSelected: false,
  // },
  // {
  //   id: 8,
  //   name: 'Driver Taxi',
  //   route: 'driver-taxi',
  //   icon: '',
  //   isSelected: false,
  // },
  {
    id: 9,
    name: 'Earning Reports',
    route: 'earning-reports',
    icon: 'icon-money',
    isSelected: false,
  },
  // {
  //   id: 10,
  //   name: 'Manage Documents',
  //   route: 'manage-documents',
  //   icon: '',
  //   isSelected: false,
  // },
  {
    id: 11,
    name: 'Reviews and Ratings',
    route: 'review-rating',
    icon: 'icon-star',
    isSelected: false,
  },
  // {
  //   id: 12,
  //   name: "God's View Location",
  //   route: 'god-view-location',
  //   icon: '',
  //   isSelected: false,
  // },
  // {
  //   id: 13,
  //   name: 'Track Users',
  //   route: 'track-users',
  //   icon: '',
  //   isSelected: false,
  // },
  {
    id: 14,
    name: 'Statement',
    route: 'statement',
    icon: 'icon-file-text2',
    isSelected: false,
  },
  // {
  //   id: 15,
  //   name: 'Promo Code',
  //   route: 'promo-code',
  //   icon: '',
  //   isSelected: false,
  // },
  // {
  //   id: 16,
  //   name: 'Push Notification',
  //   route: 'push-notification',
  //   icon: '',
  //   isSelected: false,
  // },
  // {
  //   id: 17,
  //   name: 'Site Setting',
  //   route: 'site-setting',
  //   icon: '',
  //   isSelected: false,
  // },
  {
    id: 18,
    name: 'Pages',
    route: 'pages',
    icon: 'icon-files-empty',
    isSelected: false,
  },
];

export const dashboardCards = [
  {
    _id: 0,
    groupIcon: 'fa fa-sitemap',
    groupName: 'Site Statistics',
    card: [
      {
        cardIcon: 'fa-solid fa-user',
        cardIconBGcolor: '#fff',
        cardContentHeading: 'Total Riders',
        cardContentSubheading: '329',
        cardColor: '#884A39',
        route: '/riders',
      },
      {
        cardIcon: 'icon-steering-wheel',
        cardIconBGcolor: '#fff',
        cardContentHeading: 'Total Drivers',
        cardContentSubheading: '500',
        cardColor: '#cc5500',
        route: '/drivers',
      },
      {
        cardIcon: 'icon-cab',
        cardIconBGcolor: '#fff',
        cardContentHeading: 'Vehicle',
        cardContentSubheading: '4',
        cardColor: '#9acd32',
        route: '/vehicle',
      },
      {
        cardIcon: 'icon-money',
        cardIconBGcolor: '#fff',
        cardContentHeading: 'Revenue',
        cardContentSubheading: '500',
        cardColor: '#4cbb17',
        route: '/earning-reports',
      },
    ],
  },
  {
    _id: 1,
    groupIcon: 'fa fa-list-alt',
    groupName: 'Ride Statistics',
    card: [
      {
        cardIcon: 'fa-car fa-solid',
        cardIconBGcolor: '#fff',
        cardContentHeading: 'Total',
        cardContentSubheading: '821',
        cardColor: '#29ab87',
        route: '/rides',
      },
      {
        cardIcon: 'fa-solid fa-circle-xmark',
        cardIconBGcolor: '#fff',
        cardContentHeading: 'Cancelled',
        cardContentSubheading: '104',
        cardColor: '#FF0000',
        route: '/rides',
      },
      {
        cardIcon: 'fa-sharp fa-solid fa-person-biking',
        cardIconBGcolor: '#fff',
        cardContentHeading: 'Running',
        cardContentSubheading: '500',
        cardColor: 'green',
        route: '/rides',
      },
      {
        cardIcon: 'fa-solid fa-circle-check',
        cardIconBGcolor: '#fff',
        cardContentHeading: 'Completed',
        cardContentSubheading: '329',
        cardColor: '#228b22',
        route: '/rides',
      },
    ],
  },
];

