export const menuOptions = [
  {
    id: 1,
    name: 'Dashboard',
    icon: 'fa fa-dashboard fa-fw',
    route: 'dashboard',
    isSelected: true,
  },
  {
    id: 2,
    name: 'Riders',
    route: 'riders',
    icon: 'fa-solid fa-user',
    isSelected: false,
  },
  {
    id: 3,
    name: 'Drivers',
    route: 'drivers',
    icon: 'fa-address-card',
    isSelected: false,
  },
  {
    id: 4,
    name: 'Rides',
    route: 'rides',
    icon: 'fa-solid fa-car',
    isSelected: false,
  },
  // {
  //   id: 5,
  //   name: 'Manual Ride Booking',
  //   route: 'manual-ride-booking',
  //   icon: '',
  //   isSelected: false,
  // },
  {
    id: 6,
    name: 'Vehicle Type',
    icon: '',
    route: 'vehicle-type',
    isSelected: false,
  },
  // {
  //   id: 7,
  //   name: 'Localization',
  //   route: 'localization',
  //   icon: '',
  //   isSelected: false,
  // },
  {
    id: 8,
    name: 'Driver Taxi',
    route: 'driver-taxi',
    icon: '',
    isSelected: false,
  },
  {
    id: 9,
    name: 'Earning Reports',
    route: 'earning-reports',
    icon: '',
    isSelected: false,
  },
  // {
  //   id: 10,
  //   name: 'Manage Documents',
  //   route: 'manage-documents',
  //   icon: '',
  //   isSelected: false,
  // },
  {
    id: 11,
    name: 'Reviews and Ratings',
    route: 'review-rating',
    icon: '',
    isSelected: false,
  },
  // {
  //   id: 12,
  //   name: "God's View Location",
  //   route: 'god-view-location',
  //   icon: '',
  //   isSelected: false,
  // },
  // {
  //   id: 13,
  //   name: 'Track Users',
  //   route: 'track-users',
  //   icon: '',
  //   isSelected: false,
  // },
  {
    id: 14,
    name: 'Statement',
    route: 'statement',
    icon: '',
    isSelected: false,
  },
  // {
  //   id: 15,
  //   name: 'Promo Code',
  //   route: 'promo-code',
  //   icon: '',
  //   isSelected: false,
  // },
  // {
  //   id: 16,
  //   name: 'Push Notification',
  //   route: 'push-notification',
  //   icon: '',
  //   isSelected: false,
  // },
  // {
  //   id: 17,
  //   name: 'Site Setting',
  //   route: 'site-setting',
  //   icon: '',
  //   isSelected: false,
  // },
  {
    id: 18,
    name: 'Pages',
    route: 'pages',
    icon: '',
    isSelected: false,
  },
];
